store/products/urls.py
from django.urls import path

from products.views import products, basket_add, basket_remove

# 4.2 урок, тут хорошо описано https://metanit.com/python/django/3.6.php
app_name = 'products'

urlpatterns = [
    path('', products, name='index'),
    path('category/<int:category_id>/', products, name='category'),  # 6.2 ../products/category/<category_id>/
    path('page/<int:page_number>/', products, name='paginator'),  # 6.3 ../products/paginator/<page_number>/
    path('baskets/add/<int:product_id>/', basket_add, name='basket_add'),  # 5.3 ../products/baskets/add/<product_id>
    path('baskets/remove/<int:basket_id>/', basket_remove, name='basket_remove'),  # 5.3
]

store/store/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings  # если "from store import settings" это аналогичный способ, но не все настройки подтягиваются 

from products.views import index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='index'),
    path('products/', include('products.urls', namespace='products')),  # урок 4.2 добавили include() https://metanit.com/python/django/3.6.php
    path('users/', include('users.urls', namespace='users')),  # урок 4.7 добавили path('users/'.....
]

if settings.DEBUG:  # DEBUG == True:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    # навести на static и подсказка покажет: какие импорты добавить и что передать в ф-ию static

store/users/urls.py
from django.urls import path

from users.views import login, registration, profile, logout

# 4.7 урок
app_name = 'users'

urlpatterns = [
    path('login/', login, name='login'),  # адрес будет отображаться ../users/login/
    path('registration/', registration, name='registration'),  # адрес будет отображаться ../users/registration/
    path('profile/', profile, name='profile'),  # адрес будет отображаться ../users/profile/
    # везде адрес /users/... т.к. в главном (store/urls.py) path('users/'... ) а здесь уже ответвления
    path('logout/', logout, name='logout'),  # 4.14
]

store/products/models.py
from django.db import models
# models - таблицы для БД
from users.models import User


class ProductCategory(models.Model):  # 3.3 3:10 models.Model этот класс позволяет класс Python перенести на SQL язык 
    name = models.CharField(max_length=128)  # 3.3 класс CharField говорит что переменная 'name' это строка с определенным набором символов
    description = models.TextField(null=True, blank=True)  # 3.3 TextField говорит что переменная 'description' строка с большим текстом, null-может быть пустым

    class Meta:  # 6.4  замена англ. слов в разделах на русские
        verbose_name = 'категория'
        verbose_name_plural = 'категория'

    def __str__(self):
        return self.name


class Product(models.Model):
    name = models.CharField(max_length=256)
    description = models.TextField()
    price = models.DecimalField(max_digits=10, decimal_places=2)
    quantity = models.PositiveIntegerField(default=0)
    image = models.ImageField(upload_to='products_images')  # загружай images в папку products_images (создаст автоматом)
    category = models.ForeignKey(to=ProductCategory, on_delete=models.CASCADE)
    # связываем category (через класс ForeignKey) с другим классом ProductCategory
    # класс CASCADE - удаление категории и всех вложеных (категорий и продуктов)
    # класс PROTECT - удаляет только категорию
    # класс SET_DEFAULT (+ значение которое впечатывается по умолчанию при удалении)

    class Meta:  # 6.4  замена англ слов в разделах на русские
        verbose_name = 'Продукт'
        verbose_name_plural = 'Продукты'

    def __str__(self):
        return f'Продукт: {self.name} | Категория: {self.category.name}'  # category объект класса ProductCategory и можно обратиться к ее name


class BasketQuerySet(models.QuerySet):  # 5.4 переопределяем QuerySet, добавляем два своих метода в QuerySet. Считает общее кол-во товаров и сумму каждого в корзине
    def total_sum(self):
        return sum(basket.sum() for basket in self)

    def total_quantity(self):
        return sum(basket.quantity for basket in self)


class Basket(models.Model):
    user = models.ForeignKey(to=User, on_delete=models.CASCADE)
    product = models.ForeignKey(to=Product, on_delete=models.CASCADE)
    quantity = models.PositiveSmallIntegerField(default=0)
    created_timestap = models.DateTimeField(auto_now_add=True)  # в админке зафиксировать дату добавления заказа в корзине

    objects = BasketQuerySet.as_manager()  # 5.4

    def __str__(self):
        return f'Корзина для {self.user.username} | Продукт: {self.product.name}'

    def sum(self):  # 5.4
        return self.product.price * self.quantity

store/products/views.py
from django.shortcuts import render, HttpResponseRedirect
from django.contrib.auth.decorators import login_required  # 5.5 не позволяет отрабатывать контроллеру пока не произведена авторизация (неавториз user не может добавить в корзину или зайти на страницу профайла пока не авторизирован)

from products.models import ProductCategory, Product, Basket
from users.models import User
from django.core.paginator import Paginator


def index(request):  # функция = контроллер = вьюха
    context = {'title': 'Store'}
    return render(request, 'products/index.html', context)


def products(request, category_id=None, page=1):  # приходит request это title или products или categories. C 6.2 добавили category_id. С 6.3 добавили page=1

    if category_id:  # 6.2
        category = ProductCategory.objects.get(id=category_id)
        products = Product.objects.filter(category=category)
    else:
        products = Product.objects.all()
    per_page = 3  # сколько товаров на странице
    paginator = Paginator(products, per_page)
    products_paginator = paginator.page(page)  # обращаемся к переменной paginator и через page передаем номер страницы товары которой надо отобразить, изначально 1 и первые 3 товара, стр.2-след. 3 товара
    #  products_paginator - тот же products только расширен методами для работы с Paginator()
    context = {
        'title': 'Store - Каталог',
        # 'products': Product.objects.all(), 6.2 изменяем т.к. products будет меняться из условия выбора выше в зависимости от category_id
        # 'products': products, 6.3
        'categories': ProductCategory.objects.all(),
    }
    return render(request, 'products/products.html', context)
    # render - объединяем заданный шаблон html с заданным контекстным словарем и возвращаем объект HttpResponse с этим визуализированным кодом.


@login_required  # декоратор 5.5, можно тут прописать (login_url='/users/login/')чтобы перенаправлять на регистрацию, но пропишем это все в settings внизу
def basket_add(request, product_id):
    product = Product.objects.get(id=product_id)
    basket = Basket.objects.filter(user=request.user, product=product)

    if not basket.exists():  # если корзина пуста то для user, устанавливаем для product кол-во = 1 
        Basket.objects.create(user=request.user, product=product, quantity=1)
    else:
        basket = basket.first()  # иначе товар в корзине увеличиваем на 1 и сохраняем
        basket.quantity += 1
        basket.save()

    return HttpResponseRedirect(request.META['HTTP_REFERER'])


@login_required  # декоратор 5.5, можно тут прописать (login_url='/users/login/') чтобы перенаправлять на регистрацию, но пропишем это все в settings внизу
def basket_remove(request, basket_id):
    basket = Basket.objects.get(id=basket_id)
    basket.delete()
    return HttpResponseRedirect(request.META['HTTP_REFERER'])



'''        'products': [
            {
                'image': '/static/vendor/img/products/Adidas-hoodie.png',
                'name': 'худи черного цвета с монограммами adidas Originals',
                'price': str(6090),
                'description': 'Мягкая ткань для свитшотов. Стиль и комфорт – это образ жизни',
            },
            {
                'image': '/static/vendor/img/products/Blue-jacket-The-North-Face.png',
                'name': 'Синяя куртка The North Face',
                'price': str(23725),
                'description': 'Гладкая ткань. Водонепроницаемое покрытие. Легкий и теплый пуховый наполнитель.',
            },
            {
                'image': '/static/vendor/img/products/Brown-sports-oversized-top-ASOS-DESIGN.png',
                'name': 'Коричневый спортивный oversized-топ ASOS DESIGN',
                'price': str(3390),
                'description': 'Материал с плюшевой текстурой. Удобный и мягкий.',
            },
            {
                'image': '/static/vendor/img/products/Black-Nike-Heritage-backpack.png',
                'name': 'Черный рюкзак Nike Heritage',
                'price': str(2340),
                'description': 'Плотная ткань. Легкий материал.',
            },
            {
                'image': '/static/vendor/img/products/Black-Dr-Martens-shoes.png',
                'name': 'Черные туфли на платформе с 3 парами люверсов Dr Martens 1461 Bex',
                'price': str(13590),
                'description': 'Гладкий кожаный верх. Натуральный материал.',
            },
            {
                'image': '/static/vendor/img/products/Dark-blue-wide-leg-ASOs-DESIGN-trousers.png',
                'name': 'Темно-синие широкие строгие брюки ASOS DESIGN',
                'price': str(2890),
                'description': 'Легкая эластичная ткань сирсакер Фактурная ткань.',
            }
        ]
    }
    return render(request, 'products/products.html', context)'''

store/products/templates/products/base.html
{% load static %}  
<!--  {% load static %} загружает путь до папки static, путь BASE_DIR / 'static' из settings -->

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>{{ title }}</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    {% block css %} {% endblock %}  <!--2.6 блог подставляется ИЗ index-->
</head>

<body>

<!-- Navigation -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container">
        <a class="navbar-brand" href="{% url 'index' %}">Store</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive"
                aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'products:index' %}">Каталог <i class="fas fa-shopping-bag"></i> </a>
                </li>
                {% if user.is_authenticated %}  <!-- 4.14 чтобы показывалась панель Профиль Заказы и Выйти для авторизированого usera-->
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                        data-bs-toggle="dropdown" aria-expanded="false">
                            <i class="fas fa-user-circle"></i>
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <li>
                                <a class="dropdown-item" href="{% url 'users:profile' %}">Профиль</a>
                            </li>
                            <li><a class="dropdown-item" href="orders/orders.html">Заказы</a></li>
                            {% if user.is_superuser or user.is_staff %}  <!-- 4.14 Админ-панель видна только для superuser-->
                                <li>
                                    <a class="dropdown-item" href="{% url 'admin:index' %}"> <!-- 4.14 чтобы superuser заходил в admin-панель-->
                                        Админ-панель
                                    </a>
                                </li> 
                            {% endif %}
                            <li>
                                <hr class="dropdown-divider">
                            </li>
                            <li>
                                <a class="dropdown-item" href="{% url 'users:logout' %}">
                                    Выйти
                                </a>
                            </li>
                        </ul>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:login' %}">Войти <i class="fas fa-sign-in-alt"></i></a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

<!-- Page Content -->
{% block content %} {% endblock %}  <!--2.6 блог подставляется ИЗ products-->

{% block footer %} {% endblock %}  <!--2.6 блог подставляется ИЗ products-->

<!-- Bootstrap core JavaScript -->
<script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
<script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
        crossorigin="anonymous"></script>

<!-- FontAwesome script -->
<script src="{% static 'vendor/fontawesome/fontawesome-icons.js' %}" crossorigin="anonymous"></script>

</body>

</html>

store/products/templates/products/baskets.html
{% if baskets %}  <!--5.3--> 
    <h4 class="mt-3 mb-3 d-flex justify-content-between align-items-center mb-3">
        Корзина <span class="badge badge-secondary badge-pill">{{ baskets.total_quantity }}</span>
    </h4>
    {% for basket in baskets %}
        <div class="card mb-3">
            <div class="card-body">
                <h5 class="card-title">{{ basket.product.name }}</h5>
                <p class="card-text">{{ basket.product.description }}</p>
            </div>
            <ul class="list-group list-group-flush">
                <li class="list-group-item bg-light">
                    <div class="row text-center">
                        <div class="col-lg-4">
                            <input name="basketID" type="number" class="form-control"
                                value="{{ basket.quantity }}" min="0">
                        </div>
                        <div class="col-lg-4">{{ basket.sum }} руб</div>
                        <div class="col-lg-4">
                            <a href="{% url 'products:basket_remove' basket.id %}">
                                <i class="fas fa-trash"></i>
                            </a>
                        </div>
                    </div>
                </li>
            </ul>
        </div>
    {% endfor %}
    <div class="card mb-3">
        <div class="card-footer">
            <p class="float-left">Итого</p>
            <h4 class="float-right">{{ baskets.total_sum }} руб.</h4>
        </div>
    </div>
    <a class="btn btn-success btn-lg float-right" href="../orders/order-create.html">
        Оформить заказ
    </a>
{% else %}
    <h4 class="mt-3 mb-3 text-center">
        Корзина пуста
    </h4>
{% endif %}

store/products/templates/products/index.html
{% extends 'products/base.html' %}  <!--2.6 расширяем base-->
{% load static %}
<!--  {% load static %} загружает путь до папки static, путь BASE_DIR / 'static' из settings -->

{% block css %}
<link href="{% static 'vendor/css/index.css' %}" rel="stylesheet">  <!--2.6 подставляется В base-->
{% endblock %}

{% block content %}
    <section>
    <!--    <div class="alert alert-light text-center" role="alert">-->
    <!--        Информационное сообщение-->
    <!--    </div>-->
    <div class="container">
        <div class="row">
            <div class="col-lg-6">
                <h1 class="mt-5">Store</h1>
                <p>
                    Новые образы и лучшие бренды на Store.
                    Бесплатная доставка по всему миру! Аутлет: до -70% Собственный бренд. -20% новым покупателям.
                </p>
                <button id="start-purchase-btn" type="button" class="btn btn-lg">
                    <a id="start-purchase-link" 
                        href="{% url 'products:index' %}">     <!-- 2.5 products | 4.2 7:40 products:index -->
                        Начать покупки
                    </a>
                </button>
            </div>
        </div>
    </div>
    </section>
{% endblock %}

store/products/templates/products/products.html
{% extends 'products/base.html' %}  <!--2.6 расширяем base-->
{% load static %}
<!--  {% load static %} загружает путь до папки static, путь BASE_DIR / 'static' из settings -->

{% block css %}
    <link href="{% static 'vendor/css/products.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}  <!--2.6 блог подставляется В base-->
    <div class="container">

        <div class="row">

            <div class="col-lg-3">

                <h1 class="my-4">Store</h1>
                <div class="list-group">
                    {% for category in categories %}  <!--3.7-->
                        <a href="{% url 'products:category' category.id %}" class="list-group-item">{{ category.name }}</a> 
                    {% endfor %}
                </div>

            </div>
            <!-- /.col-lg-3 -->

            <div class="col-lg-9">

                <div id="carouselExampleIndicators" class="carousel slide my-4" data-ride="carousel">
                    <ol class="carousel-indicators">
                        <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
                        <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
                        <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
                    </ol>
                    <div class="carousel-inner" role="listbox">
                        <div class="carousel-item active">
                            <img class="d-block img-fluid" src="/static/vendor/img/slides/slide-1.jpg" alt="First slide">
                        </div>
                        <div class="carousel-item">
                            <img class="d-block img-fluid" src="/static/vendor/img/slides/slide-2.jpg" alt="Second slide">
                        </div>
                        <div class="carousel-item">
                            <img class="d-block img-fluid" src="/static/vendor/img/slides/slide-3.jpg" alt="Third slide">
                        </div>
                    </div>
                    <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                        <span class="sr-only">Previous</span>
                    </a>
                    <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                        <span class="carousel-control-next-icon" aria-hidden="true"></span>
                        <span class="sr-only">Next</span>
                    </a>
                </div>

                <div class="row">

                    {% for product in products %}
                        <div class="col-lg-4 col-md-6 mb-4">
                            <div class="card h-100">
                                <a href="#">
                                    <img class="card-img-top"
                                        src="{{ product.image.url }}"
                                        alt="">
                                </a>
                                <div class="card-body">
                                    <h4 class="card-title">
                                        <a href="#">{{ product.name }}</a>
                                    </h4>
                                    <h5>{{ product.price }} руб.</h5>
                                    <p class="card-text">{{ product.description }}</p>
                                </div>
                                <div class="card-footer text-center">  <!-- 5.3 -->
                                    <a class="btn btn-outline-success"  
                                        href="{% url 'products:basket_add' product.id %}">
                                        Отправить в корзину
                                    </a>
                                </div>
                            </div>
                        </div>
                    {% endfor %}


                </div>

                <nav aria-label="Page navigation example">
                    <ul class="pagination justify-content-center">
                        <li class="page-item {% if not products.has_previous %} disabled {% endif %}"> <!-- 6.3 -->
                            <a class="page-link"
                                href="{% if products.has_previous %} {% url 'products:paginator' products.previous_page_number %} {% else %} # {% endif %}" 
                                tabindex="-1" aria-disabled="true">
                                Предыдущая
                            </a>
                        </li>
                        {% for page in products.paginator.page_range %}  <!-- 6.3 -->
                            <li class="page-item">
                                <a class="page-link" href="{% url 'products:paginator' page %}">
                                    {{ page }}
                                </a>
                            </li>
                        {% endfor %}
                        <li class="page-item {% if not products.has_next %} disabled {% endif %}"> <!-- 6.3 -->
                            <a class="page-link" 
                                href="{% if products.has_next %} {% url 'products:paginator' products.next_page_number %} {% else %} # {% endif %}">
                                Следующая
                            </a>
                        </li>
                    </ul>
                </nav>

            </div>

        </div>

    </div>
{% endblock %}

{% block footer %}  <!--2.6 блог подставляется В base-->
    <footer class="py-5 bg-dark">
        <div class="container">
            <p class="m-0 text-center text-white">Copyright &copy; Store 2022</p>
        </div>
        <!-- /.container -->
    </footer>
{% endblock %}