store/store/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings  # если "from store import settings" это аналогичный способ, но не все настройки подтягиваются 

from products.views import index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='index'),
    path('products/', include('products.urls', namespace='products')),  # урок 4.2 добавили include() https://metanit.com/python/django/3.6.php
    path('users/', include('users.urls', namespace='users')),  # урок 4.7 добавили path('users/'.....
]

if settings.DEBUG:  # DEBUG == True:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    # навести на static и подсказка покажет: какие импорты добавить и что передать в ф-ию static

store/users/urls.py
from django.urls import path

from users.views import login, registration, profile, logout

# 4.7 урок
app_name = 'users'

urlpatterns = [
    path('login/', login, name='login'),  # адрес будет отображаться ../users/login/
    path('registration/', registration, name='registration'),  # адрес будет отображаться ../users/registration/
    path('profile/', profile, name='profile'),  # адрес будет отображаться ../users/profile/
    # везде адрес /users/... т.к. в главном (store/urls.py) path('users/'... ) а здесь уже ответвления
    path('logout/', logout, name='logout'),  # 4.14
]

store/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# 4.6 урок
class User(AbstractUser):  # AbstractUser(models.Model) наследуется от models.Model. Берем User(AbstractUser), а не User(models.Model) т.к. в AbstractUser уже созданы все поля для user'a, a если от models.Model то надо все поля создавать самому
    image = models.ImageField(upload_to='users_images', null=True, blank=True)
    # можно добавить поле пол, день рождения и тд
    # после работы с моделями всегда makemigrations!! тут мы удаляем БД такое нельзя в продакшен

store/users/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, UserChangeForm

from users.models import User


class UserLoginForm(AuthenticationForm):  # 4.8, 4.10  создаем красивые формы для регистрации (указываем где в login.html брать логин и пароль)
    username = forms.CharField(widget=forms.TextInput(attrs={  # текст в форме TextInput не скрывается в PasswordInput скрывается
        'class': "form-control py-4", 'placeholder': "Введите имя пользователя"}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'class': "form-control py-4", 'placeholder': "Введите пароль"}))

    class Meta:  # принимает доп параметры которые отвечают за то с какой моделью будет работать данная форма и какими полями
        model = User
        fields = ('username', 'password')


class UserRegistrationForm(UserCreationForm):  # 4.11
    first_name = forms.CharField(widget=forms.TextInput(attrs={
        'class': "form-control py-4", 'placeholder': "Введите имя"}))
    last_name = forms.CharField(widget=forms.TextInput(attrs={
        'class': "form-control py-4", 'placeholder': "Введите фамилию"}))
    username = forms.CharField(widget=forms.TextInput(attrs={
        'class': "form-control py-4", 'placeholder': "Введите имя пользователя"}))
    email = forms.CharField(widget=forms.EmailInput(attrs={
        'class': "form-control py-4", 'placeholder': "Введите адрес эл. почты"}))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={
        'class': "form-control py-4", 'placeholder': "Введите пароль"}))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={
        'class': "form-control py-4", 'placeholder': "Подтвердите пароль"}))

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'username', 'email', 'password1', 'password2')


class UserProfileForm(UserChangeForm):  # 4.12
    first_name = forms.CharField(widget=forms.TextInput(attrs={'class': "form-control py-4"}))
    last_name = forms.CharField(widget=forms.TextInput(attrs={'class': "form-control py-4"}))
    image = forms.ImageField(widget=forms.FileInput(attrs={'class': "custom-file-input"}), required=False)
    username = forms.CharField(widget=forms.TextInput(attrs={'class': "form-control py-4", 'readonly': True}))  # readonly неизменяемые поля в профиле
    email = forms.CharField(widget=forms.EmailInput(attrs={'class': "form-control py-4", 'readonly': True}))  # readonly неизменяемые поля в профиле

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'image', 'username', 'email')

store/users/views.py
from django.shortcuts import render, HttpResponseRedirect
from django.contrib import auth, messages
from django.urls import reverse
from django.contrib.auth.decorators import login_required  # 5.5 не позволяет отрабатывать контроллеру пока не произведена авторизация (неавториз user не может добавить в корзину или зайти на страницу профайла пока не авторизирован)

from users.forms import UserLoginForm, UserRegistrationForm, UserProfileForm
from products.models import Basket


# 4.7 урок
def login(request):  # при первом входе на страницу /users/login/ срабатывает GET запрос и преходит ниже на else которая return пустую форму для заполнения 'users/login.html'
                     # при заполнении формы и нажатии Авторизоваться срабатывает if, т.к. это POST запрос
    if request.method == "POST":
        form = UserLoginForm(data=request.POST)  # заполняем класс UserLoginForm данными из POST запроса, request.POST-это словарь
        if form.is_valid():  # тут происходит AUDIT (контроль)
            username = request.POST['username']  # если данные прошли валидацию то из словаря request.POST достаем username
            password = request.POST['password']  # ... password
            user = auth.authenticate(username=username, password=password)  # после проверки,  тут происходит AUTHENTICATION (подтверждение личности) надо достать пользователя из БД и понять существует ли он
            if user:  # == True
                auth.login(request, user)  # если нашли в БД тут происходит AUTHORISATION (Разрешение)
                return HttpResponseRedirect(reverse('index'))  # перенаправление после регистрации на главную страниц
    else:
        form = UserLoginForm()
    context = {'form': form}
    return render(request, 'users/login.html', context)


def registration(request):  # 4.11
    if request.method == "POST":
        form = UserRegistrationForm(data=request.POST)
        if form.is_valid():
            form.save()  # пишем save для формы а он уже вызовет save для объектов и сохранит все в БД (first_name.save(), last_name.save() и тд)
            messages.success(request, 'Поздравляем, вы успешно зарегистрировались!')  # 4.13 import пакет messages
            return HttpResponseRedirect(reverse('users:login'))  # перенаправляем на старницу авторизации
    else:
        form = UserRegistrationForm()
    context = {'form': form}
    return render(request, 'users/registration.html', context)


@login_required  # декоратор 5.5, можно тут прописать (login_url='/users/login/')чтобы перенаправлять на регистрацию, но пропишем это все в settings внизу
def profile(request):
    if request.method == 'POST':  # 4.12 добавялем if для варианта если user меняет first_name и last_name в профиле в лич.кабинете
        form = UserProfileForm(instance=request.user, data=request.POST, files=request.FILES)  # instance это ТЕ first_name и last_name КОТОРЫЕ мы меняем в профиле в лич.кабинете,
        # а data это данные НА КОТОРЫЕ мы меняем, которые приходят когда User меняет first_name и last_name
        # files передает изображение загруженное User'ом
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('users:profile'))  # возвращаем на ту же страницу профиля
    else:
        form = UserProfileForm(instance=request.user)  # 4.12 добавляем instance с данными user чтобы в личн.кабинете в поля небыли пустыми
    context = {
        'title': 'Store - Профиль',
        'form': form,
        'baskets': Basket.objects.filter(user=request.user),  # 5.3, а в 5.4 all() изменили не filter(user...) чтобы разделить товары по разным user'ам
    }
    return render(request, 'users/profile.html', context)


def logout(request):  # 4.14
    auth.logout(request)
    return HttpResponseRedirect(reverse('index'))

store/users/templates/users/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
    <meta name="description" content=""/>
    <meta name="author" content=""/>
    <title>Store - Авторизация</title>
    <link href="{% static 'vendor/css/auth.css' %}" rel="stylesheet"/>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/js/all.min.js"
            crossorigin="anonymous"></script>
</head>
<body class="bg-primary">
<div id="layoutAuthentication">
    <div id="layoutAuthentication_content">
        {% block content %} {% endblock %}
    </div>
</div>
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"
        crossorigin="anonymous"></script>
<script src="{% static 'vendor/js/auth-admin.js' %}"></script>
</body>
</html>

store/users/templates/users/login.html
{% extends 'users/base.html' %}

{% block content %}
    <main>
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-lg-5">
                    {% if messages or form.non_field_errors %}
                        <div class="alert alert-warning alert-dismissible fade show" role="alert"
                            style="margin-top: 50px;">
                            {% if messages %}  <!--4.13 ошибки-->
                                {% for message in messages %}
                                    {{ message }}
                                {% endfor %}
                            {% else %}
                                {{ form.non_field_errors }}
                            {% endif %}
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                    {% endif %}
                    <div class="card shadow-lg border-0 rounded-lg mt-5">
                        <div class="card-header"><h3 class="text-center font-weight-light my-4">Авторизация</h3>
                        </div>
                        <div class="card-body">
                            <form action="{% url 'users:login' %}" method="post"> <!--4.9 'form action' для работы с формами, помогает понять форме куда отправлять данные, пишем users:login отправлять в контроллер def login-->
                                {% csrf_token %}
                                <div class="form-group">
                                    <label class="small mb-1" for="{{ form.username.id_for_lable }}">   <!-- 4.10 в шаблоне можно обратиться к каждому отдельному полю формы ч/з название формы form.название_поля-->
                                        <!-- Возвращает HTML ID атрибут этого виджета для использования <label>, учитывая ID поля. Возвращает пустую строку, если ID недоступен.
                                        Этот необходимо, т.к. некоторые виджеты имеют несколько элементов HTML и, следовательно, несколько ID. В этом случае данный метод должен возвращать значение ID, соответствующее первому ID в тегах виджета. -->
                                        Имя пользователя  <!--form.название_поля.name form.название_поля.value form.название_поля.id_for_lable возвращает id поля которое по умолчанию создается по схеме id_имя_поля -->
                                    </label>
                                    {{ form.username }}  <!-- 4.10 -->
                                </div>
                                <div class="form-group">
                                    <label class="small mb-1" for="{ form.password.id_for_lable }">
                                        Пароль
                                    </label>
                                    {{ form.password }}
                                </div>
                                <div class="form-group d-flex align-items-center justify-content-between mt-4 mb-0">
                                    <a class="small" href="#">Забыли пароль?</a>
                                    <input class="btn btn-primary" type="submit" value="Авторизоваться">
                                </div>
                                <div class="form-group d-flex align-items-center justify-content-between mt-4 mb-0">
                                    <a href="#">
                                        <i class="fab fa-google fa-2x" style="color: #d9503e;"></i>
                                    </a>
                                    <a href="#">
                                        <i class="fab fa-vk fa-2x" style="color: #4a658b;"></i>
                                    </a>
                                    <a href="#">
                                        <i class="fab fa-github fa-2x" style="color: #303030;"></i>
                                    </a>
                                    <a href="#">
                                        <i class="fab fa-facebook fa-2x" style="color: #405794;"></i>
                                    </a>
                                </div>
                            </form>
                        </div>
                        <div class="card-footer text-center">
                            <div class="small"><a href="{% url 'users:registration' %}">Нужен аккаунт? Зарегистрируйся!</a></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </main>
{% endblock %}

store/users/templates/users/profile.html
{% extends 'products/base.html' %}  <!--4.12-->>
{% load static %}

{% block css %}
    <link href="{% static 'vendor/css/profile.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-lg-7">
                <h4 class="mt-3 mb-3">Профиль</h4>
                <div class="col-lg-12 text-center">
                    <img width="100" height="100"
                        src="{% if user.image %} {{ user.image.url }} {% else %} {% static 'vendor/img/users/default_avatar.jpg' %} {% endif %}"
                        class="img-thumbnail">
                </div>
                <form action="{% url 'users:profile' %}" method="post" enctype="multipart/form-data"> 
                    {% csrf_token %}
                    <div class="form-row">
                        <div class="col-lg-6">
                            <div class="form-group">
                                <label class="small mb-1" for="{{ form.first_name.id_for_lable }}">Имя</label>
                                {{ form.first_name }}
                            </div>
                        </div>
                        <div class="col-lg-6">
                            <div class="form-group">
                                <label class="small mb-1" for="{{ form.last_name.id_for_lable }}">Фамилия</label>
                                {{ form.last_name }}
                            </div>
                        </div>
                    </div>
                    <div class="form-row mb-2">
                        <div class="col-lg-12">
                            <div class="custom-file">
                                {{ form.image }}
                                <label class="custom-file-label" for="{{ form.image.id_for_lable }}">
                                    Выберите изображение
                                </label>
                            </div>
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="col-lg-6">
                            <label class="small mb-1" for="{{ form.username.id_for_lable }}">Имя пользователя</label>
                            {{ form.username }}
                        </div>
                        <div class="col-lg-6">
                            <label class="small mb-1" for="{{ form.email.id_for_lable }}">
                                Адрес электронной почты
                            </label>
                            {{ form.email }}
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="col-lg-12" style="margin-top: 33px;">
                            <input class="btn btn-info btn-block" type="submit" value="Сохранить">
                        </div>
                    </div>
                </form>
            </div>
            <div class="col-lg-5">
                <!--  5.3 удалили кусок с корзиной и перенесли в baskets.html -->
                {% include 'products/baskets.html' %}
            </div>
        </div>
    </div>
{% endblock %}

store/users/templates/users/registration.html
{% extends 'users/base.html' %}

{% block content %}
    <main>
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-lg-7">
                    {% if form.non_field_errors %}  <!--4.13 обработка ошибок -->
                        <div class="alert alert-warning alert-dismissible fade show" role="alert"
                            style="margin-top: 50px;">
                            {{ form.errors }}
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                    {% endif %}
                    <div class="card shadow-lg border-0 rounded-lg mt-5">
                        <div class="card-header"><h3 class="text-center font-weight-light my-4">Создать аккаунт</h3>
                        </div>
                        <div class="card-body">
                            <form action="{% url 'users:registration' %}" method="post"> <!-- 4.11 -->
                                {% csrf_token %}
                                <div class="form-row">
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label class="small mb-1" for="{{ form.first_name.id_for_lable }}">  <!-- 4.11 -->
                                                Имя
                                            </label>
                                            {{ form.first_name }}
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label class="small mb-1" for="{{ form.last_name.id_for_lable }}">  <!-- 4.11 -->
                                                Фамилия
                                            </label>
                                            {{ form.last_name }}
                                        </div>
                                    </div>
                                </div>
                                <div class="form-row">
                                    <div class="col-md-6">
                                        <label class="small mb-1" for="{{ form.username.id_for_lable }}">   <!-- 4.11 -->
                                            Имя пользователя
                                        </label>
                                        {{ form.username }}
                                    </div>
                                    <div class="col-md-6">
                                        <label class="small mb-1" for="{{ form.email.id_for_lable }}">  <!-- 4.11 -->
                                            Адрес электронной почты
                                        </label>
                                        {{ form.email }}
                                    </div>
                                </div>
                                <div class="form-row">
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label class="small mb-1" for="{{ form.password1.id_for_lable }}">
                                                Пароль
                                            </label>
                                            {{ form.password1 }}
                                        </div>
                                    </div>
                                    <div class="col-md-6">
                                        <div class="form-group">
                                            <label class="small mb-1" for="{{ form.password2.id_for_lable }}">
                                                Подтверждение пароля
                                            </label>
                                            {{ form.password2 }}
                                        </div>
                                    </div>
                                </div>
                                <div class="form-group mt-4 mb-0">
                                    <input class="btn btn-primary btn-block" type="submit" value="Создать аккаунт">
                                </div>
                            </form>
                        </div>
                        <div class="card-footer text-center">
                            <div class="small">
                                <a href="{% url 'users:login' %}">
                                    Уже есть аккаунт? Авторизоваться
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </main>
{% endblock %}